# Project UAV
Version 1.0

#### call packages

In [3]:
import numpy as np
import matplotlib.pyplot as plt


#### initial parameters

In [17]:
NUM_GU = 10  # number of ground users

X_MIN = 0  # minimum x-axis [meter]
X_MAX = 100  # maximum x-axis [meter]
Y_MIN = 0  # minimum y-axis [meter]
Y_MAX = 100  # maximum y-axis [mseter]


GRID_SIZE = 10  # grid size

UAV_TX_POWER = 30 # uav's transmit power in [dBm]

#### initial variables

In [ ]:
t = 0  # time [seconds]

gu_bat = np.zeros((NUM_GU,)) # battery of ground user [mWh]


#### generate variables

In [19]:
# generate ground user location randomly x,y,z [meters]
gu_x = np.random.uniform(low=X_MIN, high=X_MAX, size=(NUM_GU,))
gu_y = np.random.uniform(low=Y_MIN, high=Y_MAX, size=(NUM_GU,))
gu_z = np.zeros((NUM_GU,))

# print
gu_x, gu_y, gu_z



(array([21.76620922,  2.45978254, 64.54631437, 64.42423368, 76.55305669,
        46.92138874, 36.00619923, 36.26751275, 57.51811799, 18.09094413]),
 array([18.64197946, 39.16008871,  1.84215945, 87.99873544, 71.10299044,
        56.59357344,  0.70539646, 88.31852363, 69.05815188, 17.53727165]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

In [20]:
# generate uav location
uav_x = 0
uav_y = 0
uav_z = 10 # uav's altitude [meter]


# print
uav_x, uav_y, uav_z

(0, 0, 10)